version: '3.7'
services:
  redis-server:
    image: 'redis'
    networks:
      - full-stack-network
  hello-world-service:
    build: .
    #restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: fib
      RDS_USERNAME: fib-user
      RDS_PASSWORD: dummyfib
    networks:
      - redis-compose-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: fib-user
      MYSQL_PASSWORD: dummyfib
      MYSQL_DATABASE: fib
    networks:
      - full-stack-network

networks:
    full-stack-network: